#!/bin/sh

export DESKTOP_SESSION=gnome
export XDG_SESSION_DESKTOP=gnome
export XDG_CURRENT_DESKTOP=GNOME

$SNAP/jre/bin/java -jar -Duser.home=$SNAP_USER_COMMON $SNAP/mapollage/mapollage-$SNAP_VERSION.jar
