/*
 * Copyright 2016 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.photokml.ui.config;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import se.trixon.almond.util.Dict;
import se.trixon.photokml.profile.Profile;
import se.trixon.photokml.profile.ProfilePhoto;

/**
 *
 * @author Patrik Karlsson <patrik@trixon.se>
 */
public class ModulePhotoPanel extends ModulePanel {

    private ProfilePhoto mProfilePhoto = new ProfilePhoto(mProfile);

    /**
     * Creates new form ModulePhotoPanel
     */
    public ModulePhotoPanel() {
        initComponents();
        mTitle = Dict.PHOTO.toString();
        init();
    }

    @Override
    public StringBuilder getHeaderBuilder() {
        StringBuilder sb = new StringBuilder();

        sb.append(Dict.PHOTO.toString().toUpperCase()).append("\n");

        optAppend(sb, maxWidthCheckBox.isSelected(), String.format("%s = %s", maxWidthCheckBox.getText(), mProfilePhoto.getMaxWidthValue()));
        optAppend(sb, maxHeightCheckBox.isSelected(), String.format("%s = %s", maxHeightCheckBox.getText(), mProfilePhoto.getMaxHeightValue()));
        optAppend(sb, lowerCaseExtCheckBox.isSelected(), lowerCaseExtCheckBox.getText());

        sb.append("\n");

        return sb;
    }

    @Override
    public boolean hasValidSettings() {
        return true;
    }

    @Override
    public void restoreEnabledStates() {
        maxHeightCheckBoxActionPerformed(null);
        maxWidthCheckBoxActionPerformed(null);
        urlTextField.setEnabled(urlCheckBox.isSelected());
    }

    private void init() {

        urlTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
                saveOption();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                saveOption();
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                saveOption();
            }

            private void saveOption() {
                mProfilePhoto.setBaseUrlValue(urlTextField.getText());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        maxWidthCheckBox = new javax.swing.JCheckBox();
        maxHeightCheckBox = new javax.swing.JCheckBox();
        urlCheckBox = new javax.swing.JCheckBox();
        urlTextField = new javax.swing.JTextField();
        lowerCaseExtCheckBox = new javax.swing.JCheckBox();
        widthSpinner = new javax.swing.JSpinner();
        heightSpinner = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("se/trixon/photokml/ui/config/Bundle"); // NOI18N
        maxWidthCheckBox.setText(bundle.getString("ModulePhotoPanel.maxWidthCheckBox.text")); // NOI18N
        maxWidthCheckBox.setPreferredSize(new java.awt.Dimension(100, 18));
        maxWidthCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxWidthCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        add(maxWidthCheckBox, gridBagConstraints);

        maxHeightCheckBox.setText(bundle.getString("ModulePhotoPanel.maxHeightCheckBox.text")); // NOI18N
        maxHeightCheckBox.setPreferredSize(new java.awt.Dimension(100, 18));
        maxHeightCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxHeightCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 3, 0);
        add(maxHeightCheckBox, gridBagConstraints);

        urlCheckBox.setText(bundle.getString("ModulePhotoPanel.urlCheckBox.text")); // NOI18N
        urlCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        add(urlCheckBox, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        add(urlTextField, gridBagConstraints);

        lowerCaseExtCheckBox.setText(bundle.getString("ModulePhotoPanel.lowerCaseExtCheckBox.text")); // NOI18N
        lowerCaseExtCheckBox.setToolTipText(bundle.getString("ModulePhotoPanel.lowerCaseExtCheckBox.toolTipText")); // NOI18N
        lowerCaseExtCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowerCaseExtCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        add(lowerCaseExtCheckBox, gridBagConstraints);

        widthSpinner.setModel(new javax.swing.SpinnerNumberModel(400, 1, null, 1));
        widthSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                widthSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(widthSpinner, gridBagConstraints);

        heightSpinner.setModel(new javax.swing.SpinnerNumberModel(400, 1, null, 1));
        heightSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heightSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(heightSpinner, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void maxWidthCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxWidthCheckBoxActionPerformed
        widthSpinner.setEnabled(maxWidthCheckBox.isSelected());
        mProfilePhoto.setMaxWidth(maxWidthCheckBox.isSelected());
    }//GEN-LAST:event_maxWidthCheckBoxActionPerformed

    private void maxHeightCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxHeightCheckBoxActionPerformed
        heightSpinner.setEnabled(maxHeightCheckBox.isSelected());
        mProfilePhoto.setMaxHeight(maxHeightCheckBox.isSelected());
    }//GEN-LAST:event_maxHeightCheckBoxActionPerformed

    private void urlCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlCheckBoxActionPerformed
        urlTextField.setEnabled(urlCheckBox.isSelected());
        mProfilePhoto.setBaseUrl(urlCheckBox.isSelected());
    }//GEN-LAST:event_urlCheckBoxActionPerformed

    private void lowerCaseExtCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowerCaseExtCheckBoxActionPerformed
        mProfilePhoto.setForceLowerCaseExtension(lowerCaseExtCheckBox.isSelected());
    }//GEN-LAST:event_lowerCaseExtCheckBoxActionPerformed

    private void widthSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_widthSpinnerStateChanged
        mProfilePhoto.setMaxWidthValue((Integer) widthSpinner.getModel().getValue());
    }//GEN-LAST:event_widthSpinnerStateChanged

    private void heightSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_heightSpinnerStateChanged
        mProfilePhoto.setMaxHeightValue((Integer) heightSpinner.getModel().getValue());
    }//GEN-LAST:event_heightSpinnerStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner heightSpinner;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox lowerCaseExtCheckBox;
    private javax.swing.JCheckBox maxHeightCheckBox;
    private javax.swing.JCheckBox maxWidthCheckBox;
    private javax.swing.JCheckBox urlCheckBox;
    private javax.swing.JTextField urlTextField;
    private javax.swing.JSpinner widthSpinner;
    // End of variables declaration//GEN-END:variables

    @Override
    public void load(Profile profile) {
        mProfilePhoto = profile.getPhoto();
        maxHeightCheckBox.setSelected(mProfilePhoto.isMaxHeight());
        heightSpinner.setValue(mProfilePhoto.getMaxHeightValue());

        maxWidthCheckBox.setSelected(mProfilePhoto.isMaxWidth());
        widthSpinner.setValue(mProfilePhoto.getMaxWidthValue());

        lowerCaseExtCheckBox.setSelected(mProfilePhoto.isForceLowerCaseExtension());

        urlCheckBox.setSelected(mProfilePhoto.isBaseUrl());
        urlTextField.setText(mProfilePhoto.getBaseUrlValue());

        restoreEnabledStates();
    }

    @Override
    public void save(Profile profile) {
    }
}
