/*
 * Copyright 2016 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.photokml.ui.config;

import java.util.ResourceBundle;
import se.trixon.almond.util.BundleHelper;
import se.trixon.almond.util.Dict;
import se.trixon.almond.util.swing.dialogs.Message;
import se.trixon.photokml.Options;

/**
 *
 * @author Patrik Karlsson <patrik@trixon.se>
 */
public abstract class ModulePanel extends javax.swing.JPanel {

    protected final Options mOptions = Options.INSTANCE;
    public static final String MULTILINE_DIVIDER = "* * * * *";

    protected final String mHeaderPrefix = " + ";
    protected String mTitle;
    protected final ResourceBundle mBundle = BundleHelper.getBundle(ModulePanel.class, "Bundle");

    /**
     * Creates new form ModulePanel
     */
    public ModulePanel() {
        initComponents();
    }

    public abstract StringBuilder getHeaderBuilder();

    public String getTitle() {
        return mTitle;
    }

    public abstract boolean hasValidSettings();

    public abstract void load();

    public abstract void restoreEnabledStates();

    public abstract void save();

    public void setTitle(String title) {
        mTitle = title;
    }

    protected void invalidSettings(String message) {
        Message.error(this, Dict.INVALID_SETTING.getString(), String.format("<html><h3>%s</h3>%s", mTitle, message));
    }

    protected void optAppend(StringBuilder sb, boolean state, String string) {
        if (state) {
            sb.append(mHeaderPrefix).append(string).append("\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
