/*
 * Copyright 2018 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.mapollage.ui.config;

import javax.swing.ImageIcon;
import se.trixon.almond.util.Dict;
import se.trixon.almond.util.icons.material.MaterialIcon;
import se.trixon.mapollage.profile.Profile;
import static se.trixon.mapollage.ui.config.ModulePanel.ICON_SIZE;

/**
 *
 * @author Patrik Karlsson
 */
public class ModuleInfoPanel extends ModulePanel {

    /**
     * Creates new form ModuleInfoPanel
     */
    public ModuleInfoPanel() {
        initComponents();
        mTitle = Dict.INFORMATION.toString();
    }

    @Override
    public ImageIcon getIcon() {
        return MaterialIcon._Action.INFO_OUTLINE.get(ICON_SIZE);
    }

    @Override
    public boolean hasValidSettings() {
        return true;
    }

    @Override
    public void load(Profile profile) {
        mProfile = profile;

        if (mProfile != null) {
            viewProfile(profile);
        }
    }

    private void viewProfile(Profile profile) {
        logPanel.clear();
        int pos = profile.toDebugString().indexOf(Dict.SOURCE.toString());
        logPanel.println(profile.toDebugString().substring(pos));
        logPanel.scrollToTop();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logPanel = new se.trixon.almond.util.swing.LogPanel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.GridLayout(1, 0));
        add(logPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        viewProfile(mProfile);
    }//GEN-LAST:event_formComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private se.trixon.almond.util.swing.LogPanel logPanel;
    // End of variables declaration//GEN-END:variables

}
