name: mapollage
title: Mapollage
base: core22
version: 'REPLACE_WITH_VERSION'
summary: Mapollage is a photo kml generator for Google Earth
description: |
    Put your photos on the map.

    https://github.com/trixon/mapollage

grade: stable
architectures: [ amd64 ]
confinement: strict
icon: snap/gui/mapollage.png
license: Apache-2.0

apps:
  mapollage:
    command: mapollage/bin/mapollage
    extensions: [gnome]
    plugs:
        - home
        - removable-media
        - network

parts:
  mapollage:
    plugin: dump
    #source: https://github.com/trixon/mapollage/releases/download/v$SNAPCRAFT_PROJECT_VERSION/mapollage-$SNAPCRAFT_PROJECT_VERSION-linux.zip
    source: /root/project/mapollage-$SNAPCRAFT_PROJECT_VERSION-linux.zip
    source-type: zip

  config:
    after: [mapollage]
    plugin: nil
    override-prime: |
      snapcraftctl prime
      sed -i 's/${HOME}\/.${APPNAME}/${SNAP_USER_COMMON}\/.mapollage/' /root/prime/mapollage/bin/mapollage
      sed -i 's/${HOME}\/.cache\/${APPNAME}/${SNAP_USER_COMMON}\/.cache\/mapollage/' /root/prime/mapollage/bin/mapollage
      rm -r /root/prime/mapollage/platform/modules/lib/i386
      rm -r /root/prime/mapollage/platform/modules/lib/x86
      rm /root/prime/mapollage/platform/lib/*.dll
      rm /root/prime/mapollage/platform/lib/*.exe
      
lint:
  ignore: [library]
